apiVersion: apps/v1
kind: Deployment
metadata:
  name: embargo-s3-exporter
  labels:
    app: embargo-s3-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: embargo-s3-exporter
  template:
    metadata:
      labels:
        app: embargo-s3-exporter
    spec:
      containers:
      - name: embargo-s3-exporter
        image: slaclab/s3-bucket-usage-exporter:latest
        ports:
        - name: web
          containerPort: 8000
        env:
        - name: bucket
          value: sdfembs3
        - name: access_key
          valueFrom:
            secretKeyRef:
              name: mc-credentials
              key: access_key
        - name: secret_key
          valueFrom:
            secretKeyRef:
              name: mc-credentials
              key: secret_key
        - name: PATHS
          valueFrom:
            configMapKeyRef:
              name: paths-config
              key: PATHS
        - name: SLEEP_SCHEDULE
          value: "3600"
