namespace: embargo-s3-exporter

resources:
- deployment.yaml
- service.yaml
- serviceMonitor.yaml

secretGenerator:
- name: mc-credentials
  options:
    disableNameSuffixHash: true
  files:
  - etc/.secrets/access_key
  - etc/.secrets/secret_key

# comma separated list of paths
configMapGenerator:
  - name: paths-config
    literals:
      - PATHS= /rubin-summit-users/LATISS/,
               /rubin-summit-users/LSSTCam/,
               /rubin-summit-users/LSSTComCam/,
               /rubin-summit-users/LSSTComCam/runs/,
               /rubin-summit-users/LSSTComCamSim/,
               /rubin-summit-users/u/


