namespace: monitoring-system-dev

resources:
- deployment.yaml
- service.yaml
- serviceMonitor.yaml

secretGenerator:
- name: mc-credentials
  options:
    disableNameSuffixHash: true
  files:
  - etc/.secrets/access_key
  - etc/.secrets/secret_key

# comma separated list of paths
configMapGenerator:
  - name: paths-config
    literals:
      - PATHS= /rubin-summit-users/HSC/,
               /rubin-summit-users/LSSTComCam/runs/,
               /rubin-summit-users/u/
      - DEPTHS= 0, 1, 1
