kind: Service
apiVersion: v1
metadata:
  name: embargo-s3-exporter
  labels:
    app: embargo-s3-exporter
spec:
  selector:
    app: embargo-s3-exporter
  ports:
  - name: web
    protocol: TCP
    port: 8000
    targetPort: 8000
